apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: s1
  namespace: fluidosmesh
spec:
  host: s1
  trafficPolicy:
    outlierDetection:
      baseEjectionTime: 30s
      consecutive5xxErrors: 7
      interval: 30s
