apiVersion: v1
kind: Service
metadata:
  name: s0
  namespace: fluidosmesh
  labels:
    app: s0
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort:
    name: http-mubserviceport
  - port: 51313
    targetPort: 51313
    name: grpc-mubserviceport
  selector:
    app: s0
