apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpnetprober-edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpnetprober-edge
  template:
    metadata:
      labels:
        app: httpnetprober-edge
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - edge1
      containers:
      - name: go-httpnetprober-server
        image: msvcbench/go-httpnetprober-server:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpnetprober-edge
  name: httpnetprober-edge
spec:
  ports:
  - name: http-netprober-server-port
    nodePort: null
    port: 8080
    targetPort: 8080
    appProtocol: http
  selector:
    app: httpnetprober-edge
  type: ClusterIP