apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: net-probe-server
spec:
  hosts:
  - "*"
  gateways:
  - gateway
  tcp:
  - match:
    - port: 5201
    route:
    - destination:
        host: net-probe-server
        port:
          number: 5201