apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-probe-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net-probe-server
  template:
    metadata:
      labels:
        app: net-probe-server
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - cloud
      containers:
      - name: iperf3
        image: leodotcloud/swiss-army-knife
        ports:
        - containerPort: 5201

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: net-probe-server
  name: net-probe-server
spec:
  ports:
  - name: iperf3
    nodePort: null
    port: 5201
    targetPort: 5201
    appProtocol: tcp
  selector:
    app: net-probe-server
  type: NodePort
