apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: s8-edge1
  
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 60
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: s8-edge1
