{
 "title": "mubench-istio-edge-computing-liqo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "delta", "query": "1m" }
  ]
 },
 "panels": [
  { "title": "µBench with liqo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum by (destination_service_name) (rate(istio_request_duration_milliseconds_sum{namespace=~\"istio-ingress|edge\",destination_service_name=~\"s[0-9]*\",reporter=\"source\",response_code=\"200\"}[$delta]))) / (sum by (destination_service_name) (rate(istio_requests_total{namespace=~\"istio-ingress|edge\",destination_service_name=~\"s[0-9]*\",reporter=\"source\",response_code=\"200\"}[$delta])))",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "P90 delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (destination_app,le) (rate(istio_request_duration_milliseconds_bucket{namespace=~\"istio-ingress|edge\", reporter=\"source\"}[$delta])))",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "request rate - local",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (destination_service_name) (rate(istio_response_bytes_count{destination_workload=~\"s[0-9].*-local-*\",reporter=\"destination\",response_code=\"200\"}[$delta]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "request rate - remote",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (destination_service_name) (rate(istio_response_bytes_count{destination_workload=~\"s[0-9].*-remote1.*\",reporter=\"destination\",response_code=\"200\"}[$delta]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "local-remote network traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "sum(rate(istio_response_bytes_sum{source_workload=~\"istio-ingress|s[0-9*]-remote1\",destination_workload=~\"s[0-9*]-local\",reporter=\"destination\",response_code=\"200\"}[$delta])*8/1e6)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "remote-local network traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "sum(rate(istio_response_bytes_sum{source_workload=~\"s[0-9*]-local\",destination_workload=~\"s[0-9*]-remote1\",reporter=\"destination\",response_code=\"200\"}[$delta])*8/1e6)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "memory usage - local",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container) (sum by (container) (container_memory_usage_bytes{namespace=\"fluidosmesh\",pod=~\"s[0-9].*-local-.*\",container!=\"istio-proxy\",container!=\"\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory usage - remote",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container) (sum by (container) (container_memory_usage_bytes{namespace=\"fluidosmesh\",pod=~\"s[0-9].*-remote1-.*\",container!=\"istio-proxy\",container!=\"\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage - local",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container) (rate(container_cpu_usage_seconds_total{namespace=\"fluidosmesh\",pod=~\"s[0-9].*-local-.*\",container!=\"istio-proxy\",container!=\"\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage - remote",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container) (rate(container_cpu_usage_seconds_total{namespace=\"fluidosmesh\",pod=~\"s[0-9].*-remote1-.*\",container!=\"istio-proxy\",container!=\"\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service replicas - local",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (deployment) (kube_deployment_status_replicas{namespace=\"fluidosmesh\",deployment=~\"s[0-9].*-local.*\",container!=\"istio-proxy\",container!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service replicas - remote",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (deployment) (kube_deployment_status_replicas{namespace=\"fluidosmesh\",deployment=~\"s[0-9].*-remote1.*\",container!=\"istio-proxy\",container!=\"\"})",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "call frequency per user request - local",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (destination_service_name) (rate(istio_response_bytes_count{destination_workload=~\"s[0-9].*-local.*\",reporter=\"destination\",response_code=\"200\"}[$delta])) / scalar(sum by (destination_service_name) (rate(istio_response_bytes_count{destination_workload=~\"s0.*\",reporter=\"destination\",response_code=\"200\"}[$delta])))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "call frequency per user request - remote",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (destination_service_name) (rate(istio_response_bytes_count{destination_workload=~\"s[0-9].*-remote1\",reporter=\"destination\",response_code=\"200\"}[$delta])) / scalar(sum by (destination_service_name) (rate(istio_response_bytes_count{destination_workload=~\"s0.*\",reporter=\"destination\",response_code=\"200\"}[$delta])))",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "µbench internal delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (app_name) (increase(mub_internal_processing_latency_milliseconds_sum{}[2m])) / sum by (app_name) (increase(mub_internal_processing_latency_milliseconds_count{}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "µbench external delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (app_name) (increase(mub_external_processing_latency_milliseconds_sum{}[2m])) / sum by (app_name) (increase(mub_external_processing_latency_milliseconds_count{}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}