---
apiVersion: v1
kind: Service
metadata:
  name: redis-cart-master
  labels:
    app: redis-cart-master
spec:
  type: ClusterIP
  selector:
    app-t: redis-cart-master
  ports:
  - name: tcp-redis
    port: 6379
    targetPort: 6379
