apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iperf-edge1
  name: iperf-edge1
  namespace: iperf-edge1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf-edge1
  template:
    metadata:
      labels:
        app: iperf-edge1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - edge1
      containers:
      - image: networkstatic/iperf3:latest
        name: iperf
        ports:
        - containerPort: 5201
          name: udp-iperf
          protocol: UDP
        command:
        - iperf3
        - "-s"
        - "-p"
        - "5201"
        resources:
          requests:
            cpu: 500m
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: iperf-edge1
  name: iperf-edge1
  namespace: iperf-edge1
spec:
  ports:
  - name: udp-iperf
    port: 5201
    targetPort: 5201
    protocol: UDP
  selector:
    app: iperf-edge1
  type: ClusterIP
