apiVersion: v1
kind: Service
metadata:
  labels:
    app: s5
  name: s5
  
spec:
  ports:
  - name: http-mubserviceport
    nodePort: null
    port: 80
    targetPort: 8080
  - name: grpc-mubserviceport
    port: 51313
    targetPort: 51313
  selector:
    app: s5
  type: NodePort
