package responder

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"net/http"
	"strconv"
)

func Responder(w http.ResponseWriter, r *http.Request) {

	var s int
	length := r.URL.Query().Get("length")

	// Check if the length parameter is empty
	if length == "" {
		s = 1000 // default byte size
	} else {
		// println(length)
		s, _ = strconv.Atoi(length)
	}

	// Generate a random string of size s
	randomBytes := make([]byte, s)
	_, err := rand.Read(randomBytes)
	if err != nil {
		http.Error(w, "Failed to generate random string", http.StatusInternalServerError)
		return
	}
	randString := base64.URLEncoding.EncodeToString(randomBytes)

	// Use the generated byte array here
	// For example, you can print it:
	fmt.Fprint(w, randString[:s])
}
