{
 "title": "edge-computing-liqo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "delta", "query": "1m" },
   { "name": "istio_ingress_namespace", "query": "istio-ingress-edge1" },
   { "name": "app_namespace", "query": "fluidosmesh" },
   { "name": "istio_ingress_workload", "query": "istio-ingressgateway" }
  ]
 },
 "panels": [
  { "title": "µBench with liqo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum by (destination_service_name) (rate(istio_request_duration_milliseconds_sum{destination_service_namespace=~\"$app_namespace\",destination_service_name=~\".*\",reporter=\"source\",response_code=\"200\"}[$delta]))) / (sum by (destination_service_name) (rate(istio_requests_total{destination_service_namespace=~\"$app_namespace\",destination_service_name=~\".*\",reporter=\"source\",response_code=\"200\"}[$delta])))",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "P90 delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (destination_app,le) (rate(istio_request_duration_milliseconds_bucket{destination_service_namespace=~\"$app_namespace\", reporter=\"source\"}[$delta])))",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "request rate - cloud",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (destination_service_name) (rate(istio_response_bytes_count{destination_service_namespace=~\"$app_namespace\",destination_workload=~\".*-cloud-*\",reporter=\"destination\",response_code=\"200\"}[$delta]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "request rate - edge1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (destination_service_name) (rate(istio_response_bytes_count{destination_service_namespace=~\"$app_namespace\",destination_workload=~\".*-edge1.*\",reporter=\"destination\",response_code=\"200\"}[$delta]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "cloud-edge1 network traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "sum(rate(istio_response_bytes_sum{destination_service_namespace=~\"$app_namespace\",source_workload=~\"$istio_ingress_workload|.*-edge1\",destination_workload=~\".*-cloud\",reporter=\"destination\",response_code=\"200\"}[$delta])*8/1e6)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "edge1-cloud network traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "sum(rate(istio_response_bytes_sum{destination_service_namespace=~\"$app_namespace\",source_workload=~\".*-cloud\",destination_workload=~\".*-edge1\",reporter=\"destination\",response_code=\"200\"}[$delta])*8/1e6)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "memory usage - cloud",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container) (sum by (container) (container_memory_usage_bytes{namespace=\"$app_namespace\",pod=~\".*-cloud-.*\",container!=\"istio-proxy\",container!=\"\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory usage - edge1",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container) (sum by (container) (container_memory_usage_bytes{namespace=\"$app_namespace\",pod=~\".*-edge1-.*\",container!=\"istio-proxy\",container!=\"\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage - cloud",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container) (rate(container_cpu_usage_seconds_total{namespace=\"$app_namespace\",pod=~\".*-cloud-.*\",container!=\"istio-proxy\",container!=\"\"}[2m]))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage - edge1",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container) (rate(container_cpu_usage_seconds_total{namespace=\"fluidosmesh\",pod=~\".*-edge1-.*\",container!=\"istio-proxy\",container!=\"\"}[2m]))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service replicas - cloud",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (deployment) (kube_deployment_status_replicas{namespace=\"$app_namespace\",deployment=~\".*-cloud.*\",container!=\"istio-proxy\",container!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service replicas - edge1",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (deployment) (kube_deployment_status_replicas{namespace=\"fluidosmesh\",deployment=~\".*-edge1.*\",container!=\"istio-proxy\",container!=\"\"})",
     "legendFormat": "{{deployment}}"
    }
   ]
  }
 ]
}